name: Dependency Checks

on:
  workflow_dispatch:

env:
  TRIVY_VERSION: v0.56.1

jobs:
  dependency-checks:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: read
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        # run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4

      - name: "EPSS Policy"
        uses: advanced-security/dependabot-epss-action@v0
        with:
          token: ${{ secrets.DEPENDABOT_EPSS_GITHUB_TOKEN }}
          epss-threshold: "0"
