name: build

on:
  # push:
  #   branches:
  #     - 'master'
  workflow_dispatch:

env:
  TRIVY_VERSION: v0.56.1

jobs:
  dockerhub-build-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Only
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}

      - name: Setup Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}

      - name: Docker Image Scan with Trivy
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
        run: |
          trivy -q image --image-config-scanners secret,misconfig --scanners vuln,secret --severity HIGH,CRITICAL "ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            # ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            # ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}

  # dockerhub-sync-readme:
  #   needs: dockerhub-build-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sync README
  #       uses: docker://lsiodev/readme-sync:latest
  #       env:
  #         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         GIT_REPOSITORY: ${{ github.repository }}
  #         DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
  #         GIT_BRANCH: master
  #       with:
  #         entrypoint: node
  #         args: /opt/docker-readme-sync/sync
